# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninjas',
            new_name='Ninja',
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
