# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas', '0002_auto_20190913_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='comment',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
